### ISSUE TITLE
Will Bender now boot x84_64 NOVA ELF?

### ISSUE THREAD

**Issue by lonnietc** [blitz/bender#1]
Hi Julian,

I'm trying to update NOVA with a 64 bit compile and in my last attempts ( a while back) it had to be converted:

for the 64-bit NOVA version, the ELF binary needs to be converted to a 32-bit
binary for it to be loadable by the bender version you are using:

objcopy -SO elf32-i386 hypervisor hypervisor.elf32

I want to find the best way to upgrade either using a latest Bender or some other bootloader to boot the native NOVA 64-bit elf.

Any ideas?

**Comment by blitz** [comment]
@lonnietc Bender should be able to load a 64-bit ELF as payload. The support for that was included around 2012. If this doesn't work, I can probably help you if you share steps to reproduce the problem in a new issue.

**Comment by lonnietc** [comment]
Hi Julian,  Thanks for responding to my posts and I have been able to get some things working.

Actually, I have dug into using the NOVA+NRE direction:

https://github.com/TUD-OS/NRE

and am slowly working through ways to move the project forward as well as am currently looking into trying to port over the MUSL Clib and Bhyve VMM (from FreeBSD) over to use the NRE framework so that bhyve can be a viable VMM for NOVA.

It's slow process but, then again, there are not a lot of NOVA experts that are available and have time to work with me on this, so I am making my own progress in a slowly but surely approach.

Thanks again and have a great weekend, my friend.
